# Artificial Neural Network

### Importing the libraries

In [13]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## Part 1 - Data Preprocessing

### Importing the dataset

In [14]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [15]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [16]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Missing data check

In [17]:
dataset.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

### Splitting the dataset into the Training set and Test set

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [19]:
ann = Sequential()

### Adding the input layer and the first hidden layer

In [20]:
ann.add(Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [21]:
ann.add(Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [22]:
ann.add(Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 119389.5859
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1019.3273
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 955.2719
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 941.8323
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 875.8994
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 819.5135
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 778.1890
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 715.5823
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 658.9090
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 606.1700
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 547.5311
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 487.7548
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 440.9654
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 397.5768
Epoch 15/10

### Predicting the results of the Test set

In [29]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), axis = 1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[431.23 429.61]
 [460.01 460.64]
 [461.14 464.14]
 ...
 [473.26 471.36]
 [438.   438.22]
 [463.28 457.41]]


### Regression with Neural Networks: Calculating MSE, MAE, and R² Score

In [33]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("MAE:", mae)
print("R² Score:", r2)

MSE: 27.412590842290392
MAE: 4.113943112810826
R² Score: 0.9062778429906043
